[package]
name = "sniffer-tool"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
base64 = "0.22.1"
dialoguer = "0.11.0"
log = "0.4.27"
pcap = "2.2.0"
pretty_env_logger = "0.5.0"
prost-reflect = { version = "0.16.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
serde_repr = "0.1.20"
tokio = { version = "1.47.0", features = ["full"] }
tokio-tungstenite = "0.27.0"
protoshark = "2.0.0"
ys-sniffer = { path = "../ys-sniffer-master", features = ["tokio"] }
protox = "0.9.0"
futures-util = "0.3.31"

[patch.crates-io]
protoshark = { path = "../protoshark-master" }
